<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="user"
    nsURI="http://www.gentleware.com/poseidon/dsl/my.domain.name/" nsPrefix="user">
  <eAnnotations source="reference_to_Poseidon_DSL" references="poseidon-core.ecore#//PoseidonCoreRootElement">
    <details key="Documentation" value="This is a reference to Poseidon DSL model"/>
  </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DummyNode" eSuperTypes="poseidon-core.ecore#//PoseidonCoreNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DummyEdge" eSuperTypes="poseidon-core.ecore#//PoseidonCoreDirectedRelationship"/>
</ecore:EPackage>
