/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.gentleware.poseidon.dsl.wsn.validation;

import com.gentleware.poseidon.dsl.wsn.ActivityEdge;
import com.gentleware.poseidon.dsl.wsn.ActivityNode;

/**
 * A sample validator interface for {@link com.gentleware.poseidon.dsl.wsn.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateIn(String value);
	boolean validateOut(String value);
	boolean validateIsJointPoint(boolean value);
	boolean validateId(String value);
	boolean validateInitialNode(ActivityNode value);
	boolean validateEdges(ActivityEdge value);
}
