/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.gentleware.poseidon.dsl.wsn.validation;

import com.gentleware.poseidon.dsl.wsn.ActivationType;

/**
 * A sample validator interface for {@link com.gentleware.poseidon.dsl.wsn.ActivationProfile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivationProfileValidator {
	boolean validate();

	boolean validateSensor(ActivationType value);
	boolean validateActuator(ActivationType value);
	boolean validateDongle(ActivationType value);
	boolean validateBattery(ActivationType value);
	boolean validateNeighbors(ActivationType value);
	boolean validateSpecific(ActivationType value);
	boolean validateValue(int value);
	boolean validateCh(ActivationType value);
}
