/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.gentleware.poseidon.dsl.wsn.validation;

import com.gentleware.poseidon.dsl.wsn.macType;
import com.gentleware.poseidon.dsl.wsn.netType;
import com.gentleware.poseidon.dsl.wsn.rdcType;
import com.gentleware.poseidon.dsl.wsn.sleepType;

/**
 * A sample validator interface for {@link com.gentleware.poseidon.dsl.wsn.Parameters}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParametersValidator {
	boolean validate();

	boolean validateNetwork(netType value);
	boolean validateMac(macType value);
	boolean validateRadioduty(rdcType value);
	boolean validateSleep(sleepType value);
}
